---

cellIdPreamble: "cell-"
cellIdExtender: "@flowrpt"
cellLabelDecimalPoints: 0
datapoint: "last"
gradientMode: "none"

cells:

  link_1_2:
    dataRef: "status_enlace"
    fillColor:
      dataRef: "status_enlace"
      gradientMode: "none"
      thresholdPatterns:
        linkStatus:
          - {color: "green",  pattern: '^0$'}
          - {color: "yellow", pattern: '^1$'}
          - {color: "red",    pattern: '^2$'}
    strokeColor:
      dataRef: "status_enlace"
      gradientMode: "none"
      thresholdPatterns:
        linkStatus:
          - {color: "green",  pattern: '^0$'}
          - {color: "yellow", pattern: '^1$'}
          - {color: "red",    pattern: '^2$'}

  router_1:
    dataRef: "status_router_1"
    fillColor:
      dataRef: "status_router_1"
      gradientMode: "none"
      thresholdPatterns:
        router1Status:
          - {color: "yellow", pattern: '^1$'}
          - {color: "red",    pattern: '^[2-9][0-9]*$'}
    strokeColor:
      dataRef: "status_router_1"
      gradientMode: "none"
      thresholdPatterns:
        router1Status:
          - {color: "yellow", pattern: '^1$'}
          - {color: "red",    pattern: '^[2-9][0-9]*$'}

  router_2:
    dataRef: "status_router_2"
    fillColor:
      dataRef: "status_router_2"
      gradientMode: "none"
      thresholdPatterns:
        router2Status:
          - {color: "yellow", pattern: '^1$'}
          - {color: "red",    pattern: '^[2-9][0-9]*$'}
    strokeColor:
      dataRef: "status_router_2"
      gradientMode: "none"
      thresholdPatterns:
        router2Status:
          - {color: "yellow", pattern: '^1$'}
          - {color: "red",    pattern: '^[2-9][0-9]*$'}
