---

cellIdPreamble: "cell-"
cellIdExtender: "@flowrpt"
cellLabelDecimalPoints: 0
datapoint: "lastNotNull"
gradientMode: "none"

dataRefTransform:
  namespaced: true

cells:

  link_1_2:
    dataRef: "A.status_enlace"
    fillColor:
      dataRef: "A.status_enlace"
      gradientMode: "none"
      thresholds:
        - {color: "green",  level: 0}
        - {color: "yellow", level: 1}
        - {color: "red",    level: 2}
    strokeColor:
      dataRef: "A.status_enlace"
      gradientMode: "none"
      thresholds:
        - {color: "green",  level: 0}
        - {color: "yellow", level: 1}
        - {color: "red",    level: 2}

  router_1:
    dataRef: "A.status_router_1"
    fillColor:
      dataRef: "A.status_router_1"
      gradientMode: "none"
      thresholds:
        - {color: "default", level: 0}
        - {color: "yellow",  level: 1}
        - {color: "red",     level: 2}
    strokeColor:
      dataRef: "A.status_router_1"
      gradientMode: "none"
      thresholds:
        - {color: "default", level: 0}
        - {color: "yellow",  level: 1}
        - {color: "red",     level: 2}

  router_2:
    dataRef: "A.status_router_2"
    fillColor:
      dataRef: "A.status_router_2"
      gradientMode: "none"
      thresholds:
        - {color: "default", level: 0}
        - {color: "yellow",  level: 1}
        - {color: "red",     level: 2}
    strokeColor:
      dataRef: "A.status_router_2"
      gradientMode: "none"
      thresholds:
        - {color: "default", level: 0}
        - {color: "yellow",  level: 1}
        - {color: "red",     level: 2}
